### PR TITLE
Tm/feature/accessibility

### LINKED ISSUE #40: Accessibility
** Description **
The site should be fully accessible. There are three ways we should test this: 

1. We should get a high score on Lighthouse's accessibility audit- ideally a 100. 
2. We should navigate the site with a screen reader the tab key and make sure it works. 
3. We should explore color-blindness simulations and make sure our contrast ratios hold up.

### PR DESCRIPTION
**Pull request by thaomonster**
This PR completes accessibility to 100%. Fully tabable and ran through my color blindness extension in chrome.

### Is this a feature or Fix/Refactor?  
Feature

None.

`src/Components/App/_App.scss`  lines: 7;
` src/Components/Faq/Faq.js` lines: 22, 25, 27, 33-34, 40-41, 43-44, 47;
`src/Components/Faq/_Faq.scss ` lines: 2;
`src/Components/Selector/Selector.js` lines: 50-62;
`src/Components/Selector/_Selector.scss `lines: 1-11, 15-16, 18;

### How should this be tested?
1. `git fetch` the branch
2. run `npm start`
3. run lighthouse in the console

None.

Closes #40

### CODE REVIEW

**Review by mainlyetcetera — CHANGES_REQUESTED** [review]
Thao, this is all looking solid. I do have a favor to ask. I'm getting a warning in the terminal that the `img` in `LocationData.js` needs an alt tag. You did the one for `Faq.js`; would you mind putting one on the `LocationData.js` img please? It's on line 16.

**Comment by thaomonster** [comment]
Thanks for finding that @mainlyetcetera ! Alt is added!

**Comment by deadbelly** [comment]
This is all looking really good to me. Curious if @mainlyetcetera's issue is resolved or if I should wait to merge?

**Comment by mainlyetcetera** [comment]
Nope, now this is perfect! Sorry it took me so long to circle back to this!

**Pull request merged**
